from __future__ import annotations
import json
from sqlalchemy import select
from app.models.pack_analysis import PackAnalysis
from app.models.project import Project
from app.schemas.mod import ModEntry
from app.services.pack_intelligence import quality_report,synergy_report,performance_estimate,reputation_report
from app.services.dependency_analysis import analyze_dependencies
from app.services.hardware_intelligence import hardware_fit
def _hardware(project):return {'cpu':getattr(project,'hardware_cpu',None),'gpu':getattr(project,'hardware_gpu',None),'ram_gb':getattr(project,'target_ram_gb',None),'resolution':getattr(project,'hardware_resolution',None),'refresh_rate':getattr(project,'hardware_refresh_rate',None),'target_fps':getattr(project,'target_fps',None),'shader_preference':getattr(project,'shader_support',None),'profile':getattr(project,'hardware_profile',None)}
def analyze_mods(project,mods,source='generation'):
 quality=quality_report(mods);synergy=synergy_report(mods);performance=performance_estimate(mods,ram_gb=project.target_ram_gb,fps_target=project.target_fps,shader_support=project.shader_support);dependencies=analyze_dependencies(mods);hw=_hardware(project);hardware=hardware_fit(hw,performance);problems=dependencies['risk_count']+len(synergy['conflicts'])+(1 if hardware['status']!='fit' else 0);explanations=[{'mod':m.name,'reason':('Matches selected categories: '+', '.join(m.categories[:4])) if m.categories else 'Selected as a compatible pack candidate','performance':'Low impact' if not any(x in ' '.join(m.categories).casefold() for x in ('worldgen','particle','shader')) else 'Review impact','compatibility':'Excellent' if m.file_name and m.download_url and (m.hashes.sha1 or m.hashes.sha512) else 'Needs validation'} for m in mods];overall=max(0,round(sum(quality['scores'].values())/len(quality['scores'])-problems*4+hardware['score']*.1))
 return {'overall_score':overall,'quality':quality,'performance':performance,'synergy':synergy,'dependency_risks':dependencies,'hardware':hardware,'hardware_profile':hw,'problems':problems,'recommendations':([hardware['reason']] if hardware['status']!='fit' else [])+([f"Review {len(synergy['conflicts'])} world-generation overlaps."] if synergy['conflicts'] else [])+([f"Resolve {dependencies['risk_count']} dependency risks."] if dependencies['risk_count'] else []),'reputation':[reputation_report(mod) for mod in mods],'mod_explanations':explanations,'variants':[{'name':'Lite','tier':'lite','mods':min(50,len(mods)),'ram_gb':8,'shaders':False},{'name':'Balanced','tier':'balanced','mods':min(150,len(mods)),'ram_gb':12,'shaders':False},{'name':'Ultimate','tier':'ultimate','mods':min(350,len(mods)),'ram_gb':24,'shaders':True}],'source':source}
async def persist_analysis(db,project,source='generation'):
 mods=[ModEntry.model_validate(item) for item in json.loads(project.mods_json or '[]')];report=analyze_mods(project,mods,source);latest=(await db.execute(select(PackAnalysis).where(PackAnalysis.project_id==project.id).order_by(PackAnalysis.version.desc()).limit(1))).scalars().first();version=(latest.version+1) if latest else 1;row=PackAnalysis(project_id=project.id,version=version,overall_score=report['overall_score'],report_json=json.dumps(report),source=source);db.add(row);await db.flush();return report
