import { useEffect, useState } from 'react';
import { useNavigate, useParams } from 'react-router-dom';
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { api } from '../lib/api';
const themes=['horror','fantasy','technology','magic','adventure','rpg','survival','hardcore','exploration','vanilla+'];
const gameplay=['exploration','boss fighting','building','automation','farming','magic progression','combat','story driven','multiplayer'];
const none='';
export default function AdvancedSettings(){
 const {id}=useParams<{id:string}>(); const navigate=useNavigate(); const qc=useQueryClient(); const projectId=Number(id);
 const {data:project}=useQuery({queryKey:['project',projectId],queryFn:()=>api.getProject(projectId),enabled:Number.isFinite(projectId)});
 const [open,setOpen]=useState(false); const [theme,setTheme]=useState(''); const [styles,setStyles]=useState<string[]>([]); const [difficulty,setDifficulty]=useState(''); const [minMods,setMinMods]=useState(''); const [maxMods,setMaxMods]=useState(''); const [qol,setQol]=useState(''); const [ram,setRam]=useState(''); const [fps,setFps]=useState(''); const [gpu,setGpu]=useState(''); const [shaders,setShaders]=useState(''); const [performance,setPerformance]=useState(''); const [visual,setVisual]=useState(''); const [hardware,setHardware]=useState(''); const [multiplayer,setMultiplayer]=useState(''); const [required,setRequired]=useState(''); const [forbidden,setForbidden]=useState('');
 useEffect(()=>{if(project){setTheme(project.theme||'');setDifficulty('');setMinMods(project.minimum_mods?String(project.minimum_mods):'');setMaxMods(project.maximum_mods?String(project.maximum_mods):'');}},[project]);
 const optional=(value:string)=>value||null; const save=useMutation({mutationFn:()=>api.updateProject(projectId,{generation_prompt:JSON.stringify({advanced:{theme:optional(theme),gameplay_style:styles,difficulty:optional(difficulty),minimum_mods:minMods?Number(minMods):null,maximum_mods:maxMods?Number(maxMods):null,qol_level:optional(qol),target_ram_gb:ram?Number(ram):null,target_fps:fps?Number(fps):null,shader_support:optional(shaders),performance_preference:optional(performance),visual_quality:optional(visual),hardware_profile:optional(hardware),multiplayer_mode:optional(multiplayer),required_mods:required.split(',').map(v=>v.trim()).filter(Boolean),forbidden_mods:forbidden.split(',').map(v=>v.trim()).filter(Boolean)}})}),onSuccess:()=>{qc.invalidateQueries({queryKey:['project',projectId]});navigate(`/project/${projectId}`)}});
 const toggle=(value:string)=>setStyles(current=>current.includes(value)?current.filter(v=>v!==value):[...current,value]); if(!project)return <div className='card'>Loading advanced settings...</div>;
 const select=(label:string,value:string,setter:(v:string)=>void,values:string[])=> <label className='block text-sm text-gray-300'>{label}<select className='input mt-2' value={value} onChange={e=>setter(e.target.value)}><option value=''>None</option>{values.map(v=><option key={v}>{v}</option>)}</select></label>;
 return <div className='card max-w-5xl'><button className='text-accent mb-4' onClick={()=>setOpen(!open)}>Advanced Settings (optional) {open?'▴':'▾'}</button>{open&&<><p className='text-gray-400 mb-6'>Optional settings to optimize your modpack. Leave everything empty and just describe what you want.</p><div className='grid md:grid-cols-2 gap-5'>{select('Theme',theme,setTheme,themes)}{select('Difficulty',difficulty,setDifficulty,['easy','normal','hard','extreme','nightmare'])}<fieldset className='md:col-span-2'><legend className='text-sm text-gray-300 mb-2'>Gameplay style</legend><div className='flex flex-wrap gap-2'>{gameplay.map(v=><button type='button' key={v} onClick={()=>toggle(v)} className={`px-3 py-2 rounded border text-sm ${styles.includes(v)?'border-accent bg-accent/20 text-white':'border-surface-border text-gray-400'}`}>{v}</button>)}</div></fieldset><label className='block text-sm text-gray-300'>Minimum mods<input className='input mt-2' type='number' min='1' value={minMods} onChange={e=>setMinMods(e.target.value)}/></label><label className='block text-sm text-gray-300'>Maximum mods<input className='input mt-2' type='number' min='1' placeholder='No limit' value={maxMods} onChange={e=>setMaxMods(e.target.value)}/></label>{select('QoL level',qol,setQol,['none','normal','high','maximum'])}{select('RAM available (GB)',ram,setRam,['4','6','8','12','16'])}{select('FPS target',fps,setFps,['30','60','120','144','240'])}{select('Shader support',shaders,setShaders,['no_shaders','shader_compatible','shader_optimized'])}{select('Performance',performance,setPerformance,['performance','balanced','quality'])}{select('Visual quality',visual,setVisual,['low','medium','high','ultra'])}{select('Hardware profile',hardware,setHardware,['low_end','mid_range','high_end','extreme'])}{select('Multiplayer',multiplayer,setMultiplayer,['singleplayer','co_op','server','client_server'])}<label className='block text-sm text-gray-300 md:col-span-2'>Required mods<input className='input mt-2' value={required} placeholder='sodium, jei' onChange={e=>setRequired(e.target.value)}/></label><label className='block text-sm text-gray-300 md:col-span-2'>Forbidden mods<input className='input mt-2' value={forbidden} placeholder='optifine' onChange={e=>setForbidden(e.target.value)}/></label></div><div className='flex justify-end mt-8'><button className='btn btn-primary' disabled={save.isPending} onClick={()=>save.mutate()}>{save.isPending?'Saving...':'Save optional settings'}</button></div></>}</div>;
}
