import { useEffect, useState } from 'react';
import { useNavigate, useParams } from 'react-router-dom';
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { api } from '../lib/api';
const themes=['horror','fantasy','technology','magic','adventure','rpg','survival','hardcore','exploration','vanilla+'];
const gameplay=['exploration','boss fighting','building','automation','farming','magic progression','combat','story driven','multiplayer'];
const optionalInt=(v:string)=>v?Number(v):null; const optionalText=(v:string)=>v||null;
export default function AdvancedSettings(){
 const {id}=useParams<{id:string}>(); const navigate=useNavigate(); const qc=useQueryClient(); const projectId=Number(id); const {data:project}=useQuery({queryKey:['project',projectId],queryFn:()=>api.getProject(projectId),enabled:Number.isFinite(projectId)});
 const [open,setOpen]=useState(true),[theme,setTheme]=useState(''),[styles,setStyles]=useState<string[]>([]),[difficulty,setDifficulty]=useState(''),[minMods,setMinMods]=useState(''),[maxMods,setMaxMods]=useState(''),[qol,setQol]=useState(''),[ram,setRam]=useState(''),[fps,setFps]=useState(''),[shaders,setShaders]=useState(''),[performance,setPerformance]=useState(''),[visual,setVisual]=useState(''),[hardware,setHardware]=useState(''),[multiplayer,setMultiplayer]=useState(''),[required,setRequired]=useState(''),[forbidden,setForbidden]=useState('');
 useEffect(()=>{if(!project)return;setTheme(project.theme||'');setMinMods(project.minimum_mods?String(project.minimum_mods):'');setMaxMods(project.maximum_mods?String(project.maximum_mods):'');try{const advanced=JSON.parse(project.generation_prompt||'')?.advanced;if(!advanced)return;setTheme(advanced.theme||project.theme||'');setStyles(advanced.gameplay_style||[]);setDifficulty(advanced.difficulty||'');setMinMods(advanced.minimum_mods?String(advanced.minimum_mods):'');setMaxMods(advanced.maximum_mods?String(advanced.maximum_mods):'');setQol(advanced.qol_level||'');setRam(advanced.target_ram_gb?String(advanced.target_ram_gb):'');setFps(advanced.target_fps?String(advanced.target_fps):'');setShaders(advanced.shader_support||'');setPerformance(advanced.performance_preference||'');setVisual(advanced.visual_quality||'');setHardware(advanced.hardware_profile||'');setMultiplayer(advanced.multiplayer_mode||'');setRequired((advanced.required_mods||[]).join(', '));setForbidden((advanced.forbidden_mods||[]).join(', '));}catch{/* plain prompts remain valid */}},[project]);
 const save=useMutation({mutationFn:()=>api.updateProject(projectId,{generation_prompt:JSON.stringify({advanced:{theme:optionalText(theme),gameplay_style:styles,difficulty:optionalText(difficulty),minimum_mods:optionalInt(minMods),maximum_mods:optionalInt(maxMods),qol_level:optionalText(qol),target_ram_gb:optionalInt(ram),target_fps:optionalInt(fps),shader_support:optionalText(shaders),performance_preference:optionalText(performance),visual_quality:optionalText(visual),hardware_profile:optionalText(hardware),multiplayer_mode:optionalText(multiplayer),required_mods:required.split(',').map(v=>v.trim()).filter(Boolean),forbidden_mods:forbidden.split(',').map(v=>v.trim()).filter(Boolean)}})}),onSuccess:()=>{qc.invalidateQueries({queryKey:['project',projectId]});navigate(`/project/${projectId}`)}});
 const toggle=(v:string)=>setStyles(c=>c.includes(v)?c.filter(x=>x!==v):[...c,v]); const select=(label:string,value:string,setter:(v:string)=>void,values:string[])=> <label className='block text-sm text-gray-300'>{label}<select className='input mt-2' value={value} onChange={e=>setter(e.target.value)}><option value=''>None / AI decides</option>{values.map(v=><option key={v}>{v}</option>)}</select></label>;
 if(!project)return <div className='card'>Loading advanced settings...</div>;
 return <div className='card max-w-5xl'><button className='text-accent mb-4' onClick={()=>setOpen(!open)}>Advanced Settings (optional) {open?'▴':'▾'}</button>{open&&<><p className='text-gray-400 mb-6'>Optional settings to optimize your modpack. Leave anything empty and the AI decides from your prompt.</p><div className='grid md:grid-cols-2 gap-5'>{select('Theme',theme,setTheme,themes)}{select('Difficulty',difficulty,setDifficulty,['very_easy','easy','normal','hard','very_hard','brutal','hardcore'])}<fieldset className='md:col-span-2'><legend className='text-sm text-gray-300 mb-2'>Gameplay style</legend><div className='flex flex-wrap gap-2'>{gameplay.map(v=><button type='button' key={v} onClick={()=>toggle(v)} className={`px-3 py-2 rounded border text-sm ${styles.includes(v)?'border-accent bg-accent/20 text-white':'border-surface-border text-gray-400'}`}>{v}</button>)}</div></fieldset><label className='block text-sm text-gray-300'>Target mods<input className='input mt-2' type='number' min='1' max='300' placeholder='Automatic' value={minMods} onChange={e=>setMinMods(e.target.value)}/></label><label className='block text-sm text-gray-300'>Maximum mods<input className='input mt-2' type='number' min='1' max='300' placeholder='No limit' value={maxMods} onChange={e=>setMaxMods(e.target.value)}/></label>{select('QoL level',qol,setQol,['none','normal','high','maximum'])}{select('RAM available (GB)',ram,setRam,['2','4','6','8','12','16'])}{select('FPS target',fps,setFps,['30','60','90','120','144','240'])}{select('Shader support',shaders,setShaders,['none','optional','recommended','required'])}{select('Performance',performance,setPerformance,['high_end','low_end','balanced','maximum'])}{select('Visual quality',visual,setVisual,['low','medium','high','ultra'])}{select('Hardware profile',hardware,setHardware,['low_end','mid_range','high_end','extreme'])}{select('Multiplayer',multiplayer,setMultiplayer,['singleplayer','co_op','small_server','large_server','public_server','client_server'])}{select('World style',visual,setVisual,['vanilla_plus','overhauled','extreme','realistic','fantasy','horror','skyblock','island','apocalypse'])}{select('Progression',performance,setPerformance,['fast','normal','slow','expert','quest_driven','exploration_driven','technology_driven','magic_driven','adventure_driven'])}<label className='block text-sm text-gray-300 md:col-span-2'>Required mods<input className='input mt-2' value={required} placeholder='sodium, jei' onChange={e=>setRequired(e.target.value)}/></label><label className='block text-sm text-gray-300 md:col-span-2'>Forbidden mods<input className='input mt-2' value={forbidden} placeholder='optifine' onChange={e=>setForbidden(e.target.value)}/></label></div><div className='flex justify-end mt-8'><button className='btn btn-primary' disabled={save.isPending} onClick={()=>save.mutate()}>{save.isPending?'Saving...':'Save optional settings'}</button></div></>}</div>;
}
