import {useEffect,useState} from 'react';
import {useParams,useNavigate} from 'react-router-dom';
import {useMutation,useQuery,useQueryClient} from '@tanstack/react-query';
import {api} from '../lib/api';
import {CompatStatus,Project,ShaderSupport} from '../types';
import {ArrowLeft,Check,Download,Loader2,Play,Save,X,Zap} from 'lucide-react';

export default function ProjectBuilder(){
 const {id}=useParams<{id:string}>();const projectId=Number(id||0);const navigate=useNavigate();const qc=useQueryClient();
 const [step,setStep]=useState(1);const [prompt,setPrompt]=useState('');const [progress,setProgress]=useState<any>(null);const [report,setReport]=useState<any>();const [advanced,setAdvanced]=useState<Partial<Project>>({});
 const {data:project,isLoading,error}=useQuery({queryKey:['project',projectId],queryFn:()=>api.getProject(projectId),enabled:!!projectId});
 useEffect(()=>{if(project){setPrompt(project.generation_prompt||'');setAdvanced({target_ram_gb:project.target_ram_gb,target_fps:project.target_fps,shader_support:project.shader_support,shader_quality:project.shader_quality,resourcepack_support:project.resourcepack_support,ai_creativity:project.ai_creativity,ai_strictness:project.ai_strictness,discovery_depth:project.discovery_depth,minimum_mods:project.minimum_mods,maximum_mods:project.maximum_mods});}},[project]);
 const save=useMutation({mutationFn:()=>api.updateProject(projectId,advanced),onSuccess:()=>qc.invalidateQueries({queryKey:['project',projectId]})});
 const update=(key:string,value:any)=>setAdvanced(v=>({...v,[key]:value}));
 const run=async(quick:boolean)=>{try{await api.updateProject(projectId,{generation_prompt:prompt});quick?await api.startQuickGeneration(projectId):await api.startGeneration(projectId);setStep(3);const stop=api.streamGeneration(projectId,e=>{setProgress(e);if(e.status==='complete'||e.status==='error'){stop();setStep(e.status==='complete'?4:2);qc.invalidateQueries({queryKey:['project',projectId]})}},()=>{stop();setStep(4)},e=>{stop();alert(e.message);setStep(2)});}catch(e){alert((e as Error).message)}};
 const compat=useMutation({mutationFn:()=>api.checkCompatibility(projectId),onSuccess:r=>{setReport(r);setStep(5)},onError:e=>alert((e as Error).message)});
 const exportPack=useMutation({mutationFn:()=>api.generateModpack(projectId),onSuccess:()=>{qc.invalidateQueries({queryKey:['project',projectId]});setStep(6)},onError:e=>alert((e as Error).message)});
 if(isLoading)return <Loader2 className="w-8 h-8 animate-spin"/>;if(error||!project)return <div className="card text-red-400">Failed to load project: {(error as Error)?.message}</div>;
 const download=async()=>{const blob=await api.downloadModpack(projectId);const u=URL.createObjectURL(blob);const a=document.createElement('a');a.href=u;a.download=`${project.name}.mrpack`;a.click();URL.revokeObjectURL(u)};
 return <div><header className="flex items-center gap-4 mb-8"><button className="btn btn-secondary p-2" onClick={()=>navigate('/')}><ArrowLeft className="w-4 h-4"/></button><h1 className="text-3xl font-bold">{project.name}</h1></header>
  <div className="flex gap-4 mb-8 text-sm">{['Settings','Prompt','Generation','Mods','Compatibility','Export'].map((x,i)=><span key={x} className={step>i?'text-accent':'text-gray-500'}>{i+1}. {x}</span>)}</div>
  {step===1&&<section className="card"><h2 className="text-xl font-semibold">Advanced Configuration</h2><p className="text-gray-400 text-sm mt-2">These values are loaded from the project and saved back before generation.</p><div className="grid grid-cols-2 gap-4 mt-6"><label>RAM (GB)<input className="input mt-1" type="number" value={advanced.target_ram_gb??''} onChange={e=>update('target_ram_gb',e.target.value?Number(e.target.value):undefined)}/></label><label>Target FPS<input className="input mt-1" type="number" value={advanced.target_fps??''} onChange={e=>update('target_fps',e.target.value?Number(e.target.value):undefined)}/></label><label>Shaders<select className="input mt-1" value={advanced.shader_support||ShaderSupport.OFF} onChange={e=>update('shader_support',e.target.value)}><option value="off">Off</option><option value="optional">Optional</option><option value="enabled">Enabled</option></select></label><label>Shader quality<select className="input mt-1" value={advanced.shader_quality||'medium'} onChange={e=>update('shader_quality',e.target.value)}><option>low</option><option>medium</option><option>high</option></select></label><label>Min mods<input className="input mt-1" type="number" value={advanced.minimum_mods??''} onChange={e=>update('minimum_mods',e.target.value?Number(e.target.value):undefined)}/></label><label>Max mods<input className="input mt-1" type="number" value={advanced.maximum_mods??''} onChange={e=>update('maximum_mods',e.target.value?Number(e.target.value):undefined)}/></label><label>AI creativity<select className="input mt-1" value={advanced.ai_creativity||'balanced'} onChange={e=>update('ai_creativity',e.target.value)}><option>conservative</option><option>balanced</option><option>adventurous</option></select></label><label>Discovery depth<select className="input mt-1" value={advanced.discovery_depth||'standard'} onChange={e=>update('discovery_depth',e.target.value)}><option>shallow</option><option>standard</option><option>deep</option></select></label></div><label className="block mt-4"><input type="checkbox" checked={!!advanced.resourcepack_support} onChange={e=>update('resourcepack_support',e.target.checked)}/> Resourcepack support</label><button className="btn btn-secondary mt-6 inline-flex gap-2" onClick={()=>save.mutate()}><Save className="w-4 h-4"/> Save configuration</button><button className="btn btn-primary mt-6 float-right" onClick={()=>setStep(2)}>Next</button></section>}
  {step===2&&<section className="card"><h2 className="text-xl font-semibold">Generation Prompt</h2><textarea className="input min-h-[180px] mt-4" value={prompt} onChange={e=>setPrompt(e.target.value)} placeholder="Describe your modpack"/><div className="flex justify-between mt-6"><button className="btn btn-secondary" onClick={()=>setStep(1)}>Back</button><div className="flex gap-3"><button className="btn btn-secondary" onClick={()=>run(true)}><Zap className="w-4 h-4 inline"/> Quick pack</button><button className="btn btn-primary" onClick={()=>run(false)}><Play className="w-4 h-4 inline"/> Generate</button></div></div></section>}
  {step===3&&<section className="card"><h2 className="text-xl font-semibold">Generation</h2><p className="mt-4">{progress?.message||'Starting...'}</p></section>}
  {step===4&&<section className="card"><h2 className="text-xl font-semibold">Mods ({project.mods.length})</h2><div className="mt-4 space-y-2">{project.mods.map(m=><div className="p-3 bg-surface-overlay rounded" key={`${m.source}:${m.id}`}>{m.name}</div>)}</div><button className="btn btn-primary mt-6 float-right" onClick={()=>compat.mutate()}>Check Compatibility</button></section>}
  {step===5&&report&&<section className="card"><h2 className="text-xl font-semibold">Compatibility: {report.status}</h2>{report.errors?.map((e:string)=><p className="text-red-400 mt-2" key={e}><X className="w-4 h-4 inline"/> {e}</p>)}{report.configuration?.map((x:any)=><p className={x.status===CompatStatus.OK?'text-green-400':'text-red-400'} key={x.name}>{x.message}</p>)}{report.export_ready&&<button className="btn btn-primary mt-6" onClick={()=>exportPack.mutate()}>Generate MRPack</button>}</section>}
  {step===6&&<section className="card text-center"><Check className="w-16 h-16 text-green-400 mx-auto"/><h2 className="text-2xl font-semibold mt-4">Modpack ready</h2><button className="btn btn-primary mt-6" onClick={download}><Download className="w-4 h-4 inline"/> Download</button></section>}
 </div>;
}
