import {useEffect,useState} from 'react';
import {useParams,useNavigate} from 'react-router-dom';
import {useMutation,useQuery,useQueryClient} from '@tanstack/react-query';
import {api} from '../lib/api';
import {AIProgressEvent,CompatStatus,Project,ShaderSupport} from '../types';
import {ArrowLeft,Play,Zap,Square,Download,Check,X,AlertTriangle,Loader2,Save} from 'lucide-react';

const ProjectBuilder=()=>{
 const {id}=useParams<{id:string}>();const navigate=useNavigate();const qc=useQueryClient();const projectId=Number(id||0);
 const [step,setStep]=useState(1);const [generationPrompt,setGenerationPrompt]=useState('');const [progress,setProgress]=useState<AIProgressEvent|null>(null);const [report,setReport]=useState<any>(null);const [advanced,setAdvanced]=useState<Partial<Project>>({});
 const {data:project,isLoading,error}=useQuery({queryKey:['project',projectId],queryFn:()=>api.getProject(projectId),enabled:!!projectId});
 useEffect(()=>{if(project){setGenerationPrompt(project.generation_prompt||'');setAdvanced({target_ram_gb:project.target_ram_gb,target_fps:project.target_fps,shader_support:project.shader_support,shader_quality:project.shader_quality,resourcepack_support:project.resourcepack_support,ai_creativity:project.ai_creativity,ai_strictness:project.ai_strictness,discovery_depth:project.discovery_depth,minimum_mods:project.minimum_mods,maximum_mods:project.maximum_mods});}},[project]);
 const save=useMutation({mutationFn:()=>api.updateProject(projectId,advanced),onSuccess:()=>qc.invalidateQueries({queryKey:['project',projectId])});
 const start=(quick=false)=>{const update=api.updateProject(projectId,{generation_prompt:generationPrompt});update.then(()=>{(quick?api.startQuickGeneration(projectId):api.startGeneration(projectId)).then(()=>{setStep(3);stream();}).catch((e)=>alert(e.message));}).catch((e)=>alert(e.message));};
 const stream=()=>{const stop=api.streamGeneration(projectId,e=>{setProgress(e);if(e.status==='complete'||e.status==='error'){stop();qc.invalidateQueries({queryKey:['project',projectId]);setStep(e.status==='complete'?4:2);}},()=>{stop();setStep(4)},e=>{stop();alert(e.message);setStep(2)});};
 const compat=useMutation({mutationFn:()=>api.checkCompatibility(projectId),onSuccess:r=>{setReport(r);setStep(5)},onError:e=>alert((e as Error).message)});
 const exportPack=useMutation({mutationFn:()=>api.generateModpack(projectId),onSuccess:()=>{qc.invalidateQueries({queryKey:['project',projectId]);setStep(6)},onError:e=>alert((e as Error).message)});
 const download=async()=>{const blob=await api.downloadModpack(projectId);const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`${project?.name||'modpack'}.mrpack`;a.click();URL.revokeObjectURL(url)};
 if(isLoading)return <Loader2 className="w-8 h-8 animate-spin"/>;if(error||!project)return <div className="card text-red-400">Failed to load project</div>;
 const set=(key:string,value:any)=>setAdvanced(v=>({...v,[key]:value}));
 return <div><div className="flex items-center gap-4 mb-8"><button onClick={()=>navigate('/')} className="btn btn-secondary p-2"><ArrowLeft className="w-4 h-4"/></button><h1 className="text-3xl font-bold text-gray-100">{project.name}</h1></div>
  <div className="flex gap-3 mb-8">{['Settings','Prompt','Generation','Mods','Compatibility','Export'].map((x,i)=><span key={x} className={`text-sm ${step>=i+1?'text-accent':'text-gray-500'}`}>{i+1}. {x}</span>)}</div>
  {step===1&&<div className="card"><h2 className="text-xl font-semibold mb-6">Project Settings</h2><div className="grid grid-cols-2 gap-4 text-gray-300"><div>Minecraft: <b>{project.minecraft_version}</b></div><div>Loader: <b>{project.loader}</b></div><div>Theme: <b>{project.theme}</b></div><div>Performance: <b>{project.performance_preference}</b></div></div>
   <div className="mt-8 border border-surface-border rounded-lg p-4"><h3 className="font-semibold mb-4">Advanced Configuration</h3><div className="grid grid-cols-2 gap-4"><label>RAM (GB)<input className="input mt-1" type="number" min="1" max="128" value={advanced.target_ram_gb??''} onChange={e=>set('target_ram_gb',e.target.value?Number(e.target.value):undefined)}/></label><label>Target FPS<input className="input mt-1" type="number" min="1" max="1000" value={advanced.target_fps??''} onChange={e=>set('target_fps',e.target.value?Number(e.target.value):undefined)}/></label><label>Shader support<select className="input mt-1" value={advanced.shader_support||ShaderSupport.OFF} onChange={e=>set('shader_support',e.target.value)}><option value="off">Off</option><option value="optional">Optional</option><option value="enabled">Enabled</option></select></label><label>Shader quality<select className="input mt-1" value={advanced.shader_quality||'medium'} onChange={e=>set('shader_quality',e.target.value)}><option>low</option><option>medium</option><option>high</option></select></label><label>Minimum mods<input className="input mt-1" type="number" value={advanced.minimum_mods??''} onChange={e=>set('minimum_mods',e.target.value?Number(e.target.value):undefined)}/></label><label>Maximum mods<input className="input mt-1" type="number" value={advanced.maximum_mods??''} onChange={e=>set('maximum_mods',e.target.value?Number(e.target.value):undefined)}/></label></div><label className="block mt-4"><input type="checkbox" checked={!!advanced.resourcepack_support} onChange={e=>set('resourcepack_support',e.target.checked)}/> Include resourcepack support</label><div className="grid grid-cols-3 gap-4 mt-4"><label>Creativity<select className="input mt-1" value={advanced.ai_creativity||'balanced'} onChange={e=>set('ai_creativity',e.target.value)}><option>conservative</option><option>balanced</option><option>adventurous</option></select></label><label>Strictness<select className="input mt-1" value={advanced.ai_strictness||'balanced'} onChange={e=>set('ai_strictness',e.target.value)}><option>balanced</option><option>strict</option></select></label><label>Discovery<select className="input mt-1" value={advanced.discovery_depth||'standard'} onChange={e=>set('discovery_depth',e.target.value)}><option>shallow</option><option>standard</option><option>deep</option></select></label></div><button className="btn btn-secondary mt-5 inline-flex gap-2" onClick={()=>save.mutate()} disabled={save.isPending}><Save className="w-4 h-4"/>Save configuration</button></div><button className="btn btn-primary mt-6 float-right" onClick={()=>setStep(2)}>Next <ArrowLeft className="w-4 h-4 rotate-180 inline"/></button></div>}
  {step===2&&<div className="card"><h2 className="text-xl font-semibold mb-6">AI Generation Prompt</h2><textarea className="input min-h-[200px]" value={generationPrompt} onChange={e=>setGenerationPrompt(e.target.value)} placeholder="Describe your ideal modpack"/><div className="mt-6 flex justify-between"><button className="btn btn-secondary" onClick={()=>setStep(1)}>Back</button><div className="flex gap-3"><button className="btn btn-secondary" onClick={()=>start(true)}><Zap className="w-4 h-4 inline"/> Quick pack</button><button className="btn btn-primary" onClick={()=>start(false)}><Play className="w-4 h-4 inline"/> Generate with AI</button></div></div></div>}
  {step===3&&<div className="card"><h2 className="text-xl font-semibold mb-6">Generation Progress</h2><p>{progress?.message||'Starting...'}</p><div className="mt-6"><button className="btn btn-danger" onClick={()=>api.cancelGeneration(projectId).then(()=>setStep(2))}><Square className="w-4 h-4 inline"/> Cancel</button></div></div>}
  {step===4&&<div className="card"><h2 className="text-xl font-semibold mb-6">Mods ({project.mods.length})</h2><div className="space-y-2 max-h-[500px] overflow-y-auto">{project.mods.map(m=><div key={`${m.source}:${m.id}`} className="p-3 bg-surface-overlay rounded">{m.name}<span className="text-xs text-gray-500 ml-3">{m.categories.join(', ')}</span></div>)}</div><button className="btn btn-primary mt-6 float-right" onClick={()=>compat.mutate()} disabled={compat.isPending}>{compat.isPending?'Checking...':'Check Compatibility'}</button></div>}
  {step===5&&report&&<div className="card"><h2 className="text-xl font-semibold mb-6">Compatibility: {report.status}</h2>{report.errors?.map((x:string)=><p key={x} className="text-red-400"><X className="w-4 h-4 inline"/> {x}</p>)}{report.configuration?.map((x:any)=><p key={x.name} className={x.status===CompatStatus.OK?'text-green-400':'text-red-400'}>{x.message}</p>)}{report.export_ready&&<button className="btn btn-primary mt-6" onClick={()=>exportPack.mutate()}>Generate MRPack</button>}</div>}
  {step===6&&<div className="card text-center"><Check className="w-16 h-16 text-green-400 mx-auto"/><h2 className="text-2xl font-semibold mt-4">Modpack ready</h2><button className="btn btn-primary mt-6" onClick={download}><Download className="w-4 h-4 inline"/> Download MRPack</button></div>}
 </div>;
};export default ProjectBuilder;
